name: WakaTime

on:
  workflow_dispatch:
  schedule:
    # Runs every 2 hours
    - cron: "0 */2 * * *"

jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY_NEW }}
          SHOW_UPDATED_DATE: 'False'
          SHOW_LINES_OF_CODE: 'False'
          SHOW_TOTAL_CODE_TIME: 'False'
          SHOW_PROFILE_VIEWS: 'False'
          SHOW_COMMIT: 'False'
          SHOW_DAYS_OF_WEEK: 'False'
          SHOW_LANGUAGE: 'True'
          SHOW_OS: 'False'
          SHOW_PROJECTS: 'False'
          SHOW_TIMEZONE: 'False'
          SHOW_EDITORS: 'False'
          SHOW_SHORT_INFO: 'False'
          SHOW_LOC_CHART: 'False'
          SYMBOL_VERSION: '1'
          DEBUG_LOGGING: 'False'
